gens:
  1:
    id: wheat
    drop:
      type: wheat
      name: "<#ffc569>Wheat"
    block:
      type: hay_block
      name: "<#ffc569>&lWheat Generator"
    worth: 5
    cost: 750
  2:
    id: pumpkin
    drop:
      type: pumpkin_pie
      name: "<#fc9251>Pumpkin Pie"
    block:
      type: pumpkin
      name: "<#fc9251>&lPumpkin Generator"
    worth: 10
    cost: 3000
  3:
    id: melon
    drop:
      type: melon_slice
      name: "<#64fc63>Melon Slice"
    block:
      type: melon
      name: "<#64fc63>&lMelon Generator"
    worth: 15
    cost: 6750
  4:
    id: stone
    drop:
      type: stone_button
      name: "<#797979>Stone Chunk"
    block:
      type: stone
      name: "<#797979>&lStone Generator"
    worth: 20
    cost: 12000
  5:
    id: gravel
    drop:
      type: flint
      name: "<#484848>Flint"
    block:
      type: gravel
      name: "<#484848>&lGravel Generator"
    worth: 25
    cost: 18750
  6:
    id: coal
    drop:
      type: coal
      name: "<#212121>Coal"
    block:
      type: coal_ore
      name: "<#212121>&lCoal Generator"
    worth: 30
    cost: 27000
  7:
    id: iron
    drop:
      type: iron_ingot
      name: "<#ede3d1>Iron"
    block:
      type: iron_ore
      name: "<#ede3d1>&lIron Generator"
    worth: 35
    cost: 36750
  8:
    id: gold
    drop:
      type: gold_ingot
      name: "<#ecbf44>Gold"
    block:
      type: gold_ore
      name: "<#ecbf44>&lGold Generator"
    worth: 40
    cost: 48000
  9:
    id: redstone
    drop:
      type: redstone
      name: "<#ed4545>Redstone"
    block:
      type: redstone_ore
      name: "<#ed4545>&lRedstone Generator"
    worth: 45
    cost: 60750
  10:
    id: emerald
    drop:
      type: emerald
      name: "<#33ff69>Emerald"
    block:
      type: emerald_ore
      name: "<#33ff69>&lEmerald Generator"
    worth: 50
    cost: 75000
  11:
    id: diamond
    drop:
      type: diamond
      name: "<#3ef4f4>Diamond"
    block:
      type: diamond_ore
      name: "<#3ef4f4>&lDiamond Generator"
    worth: 55
    cost: 90750