name: GenKore
version: '${version}'
website: 'https://github.com/mpschorr/GenKore'
main: xyz.jeelzzz.genkore.GenKorePlugin
api-version: '1.20'

depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - Skript

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.8.20
  - org.jetbrains.kotlin:kotlin-reflect:1.8.20
  - com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.17.0
  - com.fasterxml.jackson.module:jackson-module-kotlin:2.17.0
  - com.google.code.gson:gson:2.8.0